/*
Offers:
	how to handle EXCEPTION for all function or for a single query inside function.
	how to use TO_NUMBER function.
	how to print exception code, error message and line number at which error occured.
	how to add/substract days from dates.

*/


CREATE OR REPLACE FUNCTION IS_RENEWAL_DEADLINE_REACHED(
    P_COVERAGE_END_DATE IN DATE,
    P_EXCHANGE_ID       IN VARCHAR2)
  RETURN BOOLEAN
IS
  V_RENEWAL_DEADLINE         DATE;   --date until which a proposal renewal is allowed
  V_OEP_TO_AND_EFF_DATE_GAP  NUMBER; --min gap required between oep to date and proposal effective date
  V_OEP_TO_AND_FROM_DATE_GAP NUMBER; --min gap required between oep to date and oep from date
  V_SHARE_TO_FROM_DATE_GAP   NUMBER; --min gap required between proposal share date and oep to date
  V_NEW_EFF_DATE             DATE;
  V_NEW_OEP_TO_DATE          DATE;
  V_NEW_OEP_FROM_DATE        DATE;
BEGIN
	--dbms_output.put_line('exchange: ' || P_EXCHANGE_ID);

	--RENEWAL_ENROLLMENT_PERIOD_TO_DATE_AND_EFFECTIVE_DATE_GAP
	BEGIN
		SELECT TO_NUMBER(VALUE) INTO V_OEP_TO_AND_EFF_DATE_GAP
		FROM SYSTEM_CONFIG SC
		JOIN CONFIGURATION_GROUP CG ON SC.CONFIG_GROUP_ID = CG.ID
		WHERE SC.KEY          = 'RENEWAL_ENROLLMENT_PERIOD_TO_DATE_AND_EFFECTIVE_DATE_GAP'
		AND SC.EXCHANGE_ID    = P_EXCHANGE_ID						--FIRST CHECK FOR EXCHANGE
		AND (CG.PORTAL        = 'BROKER' OR CG.PORTAL          = 'ALL');
	EXCEPTION
	WHEN NO_DATA_FOUND THEN
		SELECT TO_NUMBER(VALUE) INTO V_OEP_TO_AND_EFF_DATE_GAP
		FROM SYSTEM_CONFIG SC
		JOIN CONFIGURATION_GROUP CG ON SC.CONFIG_GROUP_ID = CG.ID
		WHERE SC.KEY          = 'RENEWAL_ENROLLMENT_PERIOD_TO_DATE_AND_EFFECTIVE_DATE_GAP'
		AND SC.EXCHANGE_ID    IS NULL								--SET DEFAULT VALUE IF CONFIGURATION DOES NOT EXIST FOR EXCHANGE.
		AND (CG.PORTAL        = 'BROKER' OR CG.PORTAL          = 'ALL');
	END;

	--ENROLLMENT_PERIOD_TO_DATE_AND_FROM_DATE_MIN_GAP
	BEGIN
		SELECT TO_NUMBER(VALUE) INTO V_OEP_TO_AND_FROM_DATE_GAP
		FROM SYSTEM_CONFIG SC
		JOIN CONFIGURATION_GROUP CG ON SC.CONFIG_GROUP_ID         = CG.ID
		WHERE KEY                     = 'ENROLLMENT_PERIOD_TO_DATE_AND_FROM_DATE_MIN_GAP'
		AND SC.EXCHANGE_ID    = P_EXCHANGE_ID
		AND (CG.PORTAL                = 'BROKER' OR CG.PORTAL                  = 'ALL');
	EXCEPTION
	WHEN NO_DATA_FOUND THEN
		SELECT TO_NUMBER(VALUE) INTO V_OEP_TO_AND_FROM_DATE_GAP
		FROM SYSTEM_CONFIG SC
		JOIN CONFIGURATION_GROUP CG ON SC.CONFIG_GROUP_ID         = CG.ID
		WHERE KEY                     = 'ENROLLMENT_PERIOD_TO_DATE_AND_FROM_DATE_MIN_GAP'
		AND SC.EXCHANGE_ID    IS NULL
		AND (CG.PORTAL                = 'BROKER' OR CG.PORTAL                  = 'ALL');
	END;

	--PROPOSAL_SHARE_DATE_AND_ENROLLMENT_PERIOD_FROM_DATE_GAP
	BEGIN
		SELECT TO_NUMBER(VALUE) INTO V_SHARE_TO_FROM_DATE_GAP
		FROM SYSTEM_CONFIG SC
		JOIN CONFIGURATION_GROUP CG ON SC.CONFIG_GROUP_ID         = CG.ID
		WHERE KEY                     = 'PROPOSAL_SHARE_DATE_AND_ENROLLMENT_PERIOD_FROM_DATE_GAP'
		AND SC.EXCHANGE_ID    = P_EXCHANGE_ID
		AND (CG.PORTAL                = 'BROKER' OR CG.PORTAL                  = 'ALL');
	EXCEPTION
	WHEN NO_DATA_FOUND THEN
		SELECT TO_NUMBER(VALUE) INTO V_SHARE_TO_FROM_DATE_GAP
		FROM SYSTEM_CONFIG SC
		JOIN CONFIGURATION_GROUP CG ON SC.CONFIG_GROUP_ID         = CG.ID
		WHERE KEY                     = 'PROPOSAL_SHARE_DATE_AND_ENROLLMENT_PERIOD_FROM_DATE_GAP'
		AND SC.EXCHANGE_ID    IS NULL
		AND (CG.PORTAL                = 'BROKER' OR CG.PORTAL                  = 'ALL');
	END;

	V_NEW_EFF_DATE      := P_COVERAGE_END_DATE + 1;
	V_NEW_OEP_TO_DATE   := V_NEW_EFF_DATE      - V_OEP_TO_AND_EFF_DATE_GAP;
	V_NEW_OEP_FROM_DATE := V_NEW_OEP_TO_DATE   - V_OEP_TO_AND_FROM_DATE_GAP;
	V_RENEWAL_DEADLINE  := V_NEW_OEP_FROM_DATE - V_SHARE_TO_FROM_DATE_GAP;

	--dbms_output.put_line('V_NEW_EFF_DATE: ' || V_NEW_EFF_DATE || ', V_NEW_OEP_TO_DATE: ' || V_NEW_OEP_TO_DATE || ', V_NEW_OEP_FROM_DATE: ' || V_NEW_OEP_FROM_DATE);
	--dbms_output.put_line('deadlie date: ' || V_RENEWAL_DEADLINE);

	
	IF V_RENEWAL_DEADLINE is not null and V_RENEWAL_DEADLINE < SYSDATE THEN
	  RETURN TRUE;
	ELSE
	  RETURN FALSE;
	END IF;
EXCEPTION
	WHEN others THEN
	  DBMS_OUTPUT.PUT_LINE (SQLCODE || ' ' || SUBSTR(SQLERRM, 1, 64) || ' ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
	  RETURN TRUE;
END;